apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auth-backend-config
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    port: 3001
    type: HTTP
    requestPath: /healthz

