apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonsaekim-auth
  labels:
    app: sonsaekim-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonsaekim-auth
  template:
    metadata:
      labels:
        app: sonsaekim-auth
    spec:
      containers:
        - name: sonsaekim-auth
          image: mminnn28/sswu_sonsaekim-auth:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    cloud.google.com/backend-config: '{"default": "auth-backend-config"}'
spec:
  selector:
    app: sonsaekim-auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
